ENVIRONMENT:
APP:
  NAME:
  URL:
  DOMAIN: 'localhost'
  PORT: 43000
  CORS_ENABLED:
  SWAGGER:
    ENABLED: true
    DESCRIPTION:
    VERSION:
    PATH:
  JWT:
    ACCESS_SECRET:
    REFRESH_SECRET:
    EXPIRES_IN:
    REFRESH_IN:
  BCRYPT_SALT_ROUNDS:

  GRAPHQL:
    PLAYGROUND_ENABLED:
    DEBUG:
    SCHEMA_DESTINATION:
    SORT_SCHEMA:

Akun:
  ASET:
    ASET LANCAR:
      KAS DAN SETARA KAS
      SURAT BERHARGA
      PIUTANG
      PERSEDIAAN
      PERLENGKAPAN
      BEBAN DIBAYAR DI MUKA
      UANG MUKA
      INVESTASI JANGKA PENDEK
    ASET TIDAK LANCAR:
      ASET TETAP
      ASET TIDAK LANCAR LAINNYA
      AKUMULASI PENYUSUTAN
      Investasi Jangka Panjang
      REKENING ANTAR UNIT
      Aset Tidak Berwujud

  LIABILITAS:
    LIABILITAS JANGKA PENDEK:
      UTANG USAHA
      UTANG LEMBAGA KEUANGAN
      UTANG PAJAK
      UANG TITIPAN
      PENDAPATAN DITERIMA DI MUKA
      BEBAN YANG MASIH HARUS DIBAYAR
      UTANG JANGKA PENDEK LAINNYA
      Pinjaman bank
      Utang kepada pemasok
      Pajak yang belum dibayar
      Gaji yang belum dibayar
      Obligasi
      Sewa pembiayaan
    LIABILITAS JANGKA PANJANG:
      UTANG JANGKA PANJANG LEMBAGA KEUANGAN
      UTANG JANGKA PANJANG LAINNYA
      REKENING ANTAR UNIT

  ASET NETO:
    Aset Neto Terikat Permanen
    Aset Neto Terikat Temporer
    Aset Neto Tidak Terikat


  PENDAPATAN:
    PENERIMAAN ZISWAF:
      PENERIMAAN ZISWAF
      PENERIMAAN ZAKAT
      PENERIMAAN INFAQ
      PENERIMAAN SHODAQOH
      PENERIMAAN WAQAF
      PENERIMAAN FIDYAH
    PENERIMAAN USAHA:

    PENERIMAAN PENDIDIKAN:
    PENGGALANGAN DANA:
    PENERIMAAN LAINNYA:
    ASET NETO YANG BERAKHIR PEMBATASANNYA:
      PEMENUHAN PROGRAM PEMBATASAN
      PEMENUHAN PEMBATASAN PEMEROLEHAN ASET TETAP
      BERAKHIRNYA PEMBATASAN WAKTU


  BEBAN:
    PENYALURAN ZISWAF
    BEBAN SDM
    BEBAN NON SDM
    KERUGIAN AKIBAT KEBAKARAN
    KERUGIAN AKTUARIAL DAN KEWAJIBAN TAHUNAN

